import { AllList, Jumbotron, ListPosts, ListUsers } from "@/components";
import Head from "next/head";

export default function Home({ posts, users }) {
  return (
    <>
      <Head>
        <title>Test Syanpsis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Jumbotron />

      <div className="hidden md:flex mt-14">
        <ListPosts posts={posts} />
        <ListUsers users={users} />
      </div>

      <div className="md:hidden">
        <AllList posts={posts} users={users} />
      </div>
    </>
  );
}

export async function getServerSideProps(context) {
  console.log(context.resolvedUrl);
  try {
    const resPosts = await fetch("https://gorest.co.in/public/v2/posts", {
      headers: {
        Authorization:
          "Bearer 87e000ad77072d306a17b62d17566486247c44a34a13f0541fa79745640d09cb",
        "Content-Type": "application/json",
      },
    });
    const dataPosts = await resPosts.json();

    const resUsers = await fetch(`https://gorest.co.in/public/v2/users`, {
      headers: {
        Authorization:
          "Bearer 87e000ad77072d306a17b62d17566486247c44a34a13f0541fa79745640d09cb",
        "Content-Type": "application/json",
      },
    });
    const dataUsers = await resUsers.json();
    return { props: { posts: dataPosts, users: dataUsers } };
  } catch (error) {
    console.log(error);
  }
}
